### ISSUE TITLE
Grida outcome?

### ISSUE THREAD

**Issue by stylessh** [gridaco/grida#45]
Hello, this project looks incredible.

I just want to ask if this is still in development and willing to go out!

**Comment by softmarshmallow** [comment]
Hey @stylessh . We're currently focusing on our code engine (design to code)
Till then, this repo will not be our major ongoing project.

You can check the code project here - https://github.com/gridaco/code

**Comment by stylessh** [comment]
@softmarshmallow thanks for the response!

Will you guys still gonna release the beta for this year (as it says in the docs)?

**Comment by softmarshmallow** [comment]
Yes. you can expect the beta, at least a private beta in this year.
Press watch on github for these events :)
